# Minimal qtile starting point — customize freely.
# Autostart (wallpaper + screen locker) lives in ~/.config/qtile/autostart.sh,
# generated by home-manager so it can hold the nix store paths.
import os
import subprocess

from libqtile import bar, layout, widget, hook
from libqtile.config import Click, Drag, Group, Key, Screen
from libqtile.lazy import lazy

mod = "mod4"  # Super
terminal = "alacritty"


@hook.subscribe.startup_once
def autostart():
    subprocess.Popen([os.path.expanduser("~/.config/qtile/autostart.sh")])


keys = [
    Key([mod], "Return", lazy.spawn(terminal), desc="Launch terminal"),
    Key([mod], "d", lazy.spawn("rofi -show drun"), desc="App launcher"),
    Key([mod], "w", lazy.window.kill(), desc="Close window"),
    Key([mod], "l", lazy.spawn("loginctl lock-session"), desc="Lock screen"),
    Key([mod, "control"], "r", lazy.reload_config(), desc="Reload qtile"),
    Key([mod, "control"], "q", lazy.shutdown(), desc="Quit qtile"),
    # focus / layout
    Key([mod], "j", lazy.layout.down()),
    Key([mod], "k", lazy.layout.up()),
    Key([mod], "h", lazy.layout.left()),
    Key([mod], "space", lazy.layout.next()),
]

groups = [Group(i) for i in "123456789"]
for i in groups:
    keys += [
        Key([mod], i.name, lazy.group[i.name].toscreen(), desc=f"Switch to group {i.name}"),
        Key([mod, "shift"], i.name, lazy.window.togroup(i.name, switch_group=True)),
    ]

layouts = [
    layout.Columns(border_width=2, margin=6),
    layout.Max(),
]

screens = [
    Screen(
        top=bar.Bar(
            [
                widget.GroupBox(),
                widget.Prompt(),
                widget.WindowName(),
                widget.Clock(format="%Y-%m-%d %H:%M"),
                widget.Systray(),
            ],
            24,
        ),
    ),
]

mouse = [
    Drag([mod], "Button1", lazy.window.set_position_floating(), start=lazy.window.get_position()),
    Drag([mod], "Button3", lazy.window.set_size_floating(), start=lazy.window.get_size()),
    Click([mod], "Button2", lazy.window.bring_to_front()),
]

# Standard qtile boilerplate.
dgroups_key_binder = None
dgroups_app_rules = []
follow_mouse_focus = True
bring_front_click = False
cursor_warp = False
floating_layout = layout.Floating()
auto_fullscreen = True
focus_on_window_activation = "smart"
reconfigure_screens = True
auto_minimize = True
wmname = "LG3D"
